export const ActionTypes = {
    ON_LOGIN : 'ON_LOGIN',
    ON_REGISTER : 'ON_REGISTER',
    ON_LOGIN_SUCCESS : 'ON_LOGIN_SUCCESS',
    ON_REGISTER_SUCCESS : 'ON_REGISTER_SUCCESS',
    ON_LOGIN_FAILED : 'ON_LOGIN_FAILED',
    ON_REGISTER_FAILED : 'ON_REGISTER_FAILED',
    RESET_STATUS_TEXT : 'RESET_STATUS_TEXT',

    ON_LOAD_BOOKS : 'ON_LOAD_BOOKS_SUCCESS',
    ON_LOAD_BOOKS_FAILED : 'ON_LOAD_BOOKS_FAILED',
    ON_LOAD_BOOKS_SUCCESS : 'ON_LOAD_BOOKS_SUCCESS',

    ON_LOAD_AUTHORS : 'ON_LOAD_AUTHORS',
    ON_LOAD_AUTHORS_SUCCESS : 'ON_LOAD_AUTHORS_SUCCESS',
    ON_LOAD_AUTHORS_FAILED : 'ON_LOAD_AUTHORS_FAILED',

    ON_ADD_BOOK : 'ON_ADD_BOOK',
    ON_ADD_BOOK_SUCCESS : 'ON_ADD_BOOK_SUCCESS',
    ON_ADD_BOOK_FAILED : 'ON_ADD_BOOK_FAILED',

    ON_EDIT_BOOK : 'ON_EDIT_BOOK',
    ON_EDIT_BOOK_SUCCESS : 'ON_EDIT_BOOK_SUCCESS',
    ON_EDIT_BOOK_FAILED : 'ON_EDIT_BOOK_FAILED',

    ON_DELETE_BOOK : 'ON_DELETE_BOOK',
    ON_DELETE_BOOK_SUCCESS : 'ON_DELETE_BOOK_SUCCESS',
    ON_DELETE_BOOK_FAILED : 'ON_DELETE_BOOK_FAILED'
}